//
// Created by filipz on 10/25/20.
//

#ifndef CPP_UNIVERSITY_ASSIGMENT_BUSINESSSERVICE_H
#define CPP_UNIVERSITY_ASSIGMENT_BUSINESSSERVICE_H


class BusinessService {

};


#endif //CPP_UNIVERSITY_ASSIGMENT_BUSINESSSERVICE_H
