#ifndef CPP_UNIVERSITY_ASSIGMENT_CRUDBUSINESS_H
#define CPP_UNIVERSITY_ASSIGMENT_CRUDBUSINESS_H


using namespace std;
class CRUDBusiness{
private:

};

#endif //CPP_UNIVERSITY_ASSIGMENT_CRUDBUSINESS_H
